services:
  frontend:
    platform: linux/amd64
    image: m1thrandir/pollz-frontend
    build:
      context: frontend
    environment:
      - API_SOURCE=http://backend:8081
    ports:
      - "3000:3000"
    networks:
      - pollz-network
    depends_on:
      - backend
      - db
  backend:
    platform: linux/amd64
    image: m1thrandir/pollz-backend
    build:
      context: backend
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8081:8081"
    networks:
      - pollz-network
    depends_on:
      - db
  db:
    image: postgres:17.4
    env_file:
      - path: ./.env
        required: true
    volumes:
      - db_pollz:/var/lib/postgresql/data
      - ./scripts/db-healthcheck.sh:/usr/local/bin/healthcheck.sh
    ports:
      - "5432:5432"
    networks:
      - pollz-network
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  pollz-network:
    driver: bridge
volumes:
  db_pollz:
