services:
  frontend:
    platform: linux/amd64
    image: m1thrandir/pollz-frontend
    build:
      context: frontend
    ports:
      - "3030:3000"
    networks:
      - pollz-network
    depends_on:
      - backend
      - db
  backend:
    platform: linux/amd64
    image: m1thrandir/pollz-backend
    build:
      context: backend
    environment:
      DB_SOURCE: db:5432
      ENVIRONMENT: production
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - pollz-network
    depends_on:
      - db
  db:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db-healthcheck.sh:/usr/local/bin/healthcheck.sh
    ports:
      - "5432:5432"
    networks:
      - pollz-network
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  pollz-network:
    driver: bridge
volumes:
  postgres-data:
